VetClinicFinal/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using VetClinic.Data;
using VetClinic.Data.Entities;
using VetClinic.Helpers;
using VetClinic.Models;
using VetClinicFinal.Helpers;

namespace VetClinic.Controllers
{

    public class AnimalsController : Controller
    {

        private readonly IAnimalRepository _animalRepository;
        private readonly IUserHelper _userHelper;
        private readonly IClientRepository _clientRepository;
        private readonly IBlobHelper _blobHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly IAppointmentRepository _appointmentRepository;

        public AnimalsController(IAnimalRepository animalRepository, IUserHelper userHelper, IClientRepository clientRepository, 
            IBlobHelper blobHelper, IConverterHelper converterHelper, IAppointmentRepository appointmentRepository)
        {
            _animalRepository = animalRepository;
            _userHelper = userHelper;
            _clientRepository = clientRepository;
            _blobHelper = blobHelper;
            _converterHelper = converterHelper;
            _appointmentRepository = appointmentRepository;
        }


        [Authorize(Roles = "Employee,Client")]
        // GET: AnimalsController
        public IActionResult Index()
        {
            return View(_animalRepository.GetAll().Include(p => p.Owner));

        }

        [Authorize(Roles = "Employee,Client")]
        // GET: AnimalsController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("AnimalNotFound");
            }

            var animal = await _animalRepository.GetByIdAnimalAsync(id.Value);

            if (animal == null)
            {
                return new NotFoundViewResult("AnimalNotFound");
            }

            return View(animal);
        }

        [Authorize(Roles = "Employee,Client")]
        // GET: AnimalsController/Create
        public IActionResult Create()
        {
            var count = _clientRepository.GetAll().Count();

            if(count == 0)
            {
                TempData["Message"] = "You need to create an Owner first";

                return RedirectToAction(nameof(Index));
            }
            else
            {
                var model = new AddAnimalViewModel{
                    Owners = _animalRepository.GetComboOwners()
                };

                TempData["Message"] = "";

                return View(model);
            }
        }

        [Authorize(Roles = "Employee,Client")]
        // POST: AnimalsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddAnimalViewModel model)
        {
            if (ModelState.IsValid)
            {
                Guid imageId = Guid.Empty;

                if (model.ImageFile != null && model.ImageFile.Length > 0)
                {
                    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "animals");
                }

                var animal = _converterHelper.ToAnimal(model, imageId, true);

                await _animalRepository.CreateAsync(animal);

                return RedirectToAction(nameof(Index));
            }

            return View(model);

        }

        [Authorize(Roles = "Employee,Client")]
        // GET: AnimalsController/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("AnimalNotFound");
            }

            var animal = await _animalRepository.GetByIdAnimalAsync(id.Value);

            if (animal == null)
            {
                return new NotFoundViewResult("AnimalNotFound");
            }
            return View(animal);
        }

        [Authorize(Roles = "Employee,Client")]
        // POST: AnimalsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Animal animal)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    Guid imageId = animal.ImageId;

                    if (animal.ImageFile != null && animal.ImageFile.Length > 0)
                    {
                        imageId = await _blobHelper.UploadBlobAsync(animal.ImageFile, "animals");

                        animal.ImageId = imageId;
                    }

                    await _animalRepository.UpdateAsync(animal);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _animalRepository.ExistsAsync(animal.Id))
                    {
                        return new NotFoundViewResult("AnimalNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(animal);
        }

        [Authorize(Roles = "Employee")]
        // GET: AnimalsController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("Animal Not Found");
            }

            var veicule = await _animalRepository.GetByIdAnimalAsync(id.Value);

            if (veicule == null)
            {
                return new NotFoundViewResult("Animal Not Found");
            }

            return View(veicule);
        }

        [Authorize(Roles = "Employee")]
        // POST: AnimalsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var animal = await _animalRepository.GetByIdAnimalAsync(id);

            var count = _appointmentRepository.GetAll().Count();

            for(int i = 1; i <= count; i++)
            {
                var appointment = await _appointmentRepository.GetByIdAsync(i);

                if(appointment.AnimalId == id)
                {
                    TempData["Message"] = "The animal cannot be deleted because it has an appointment!"; 

                    return RedirectToAction(nameof(Index));
                }
            }

            await _animalRepository.DeleteAsync(animal);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult AnimalNotFound()
        {
            return View();
        }
    }
}

VetClinicFinal/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using VetClinic.Data;
using VetClinic.Data.Entities;
using VetClinic.Helpers;
using VetClinicFinal.Helpers;

namespace VetClinic.Controllers
{
    public class ClientsController : Controller
    {
        private readonly IClientRepository _clientRepository;
        private readonly IUserHelper _userHelper;
        private readonly IMailHelper _mailHelper;
        private readonly IAnimalRepository _animalRepository;

        public ClientsController(IClientRepository clientRepository, IUserHelper userHelper, IMailHelper mailHelper, IAnimalRepository animalRepository)
        {
            _clientRepository = clientRepository;
            _userHelper = userHelper;
            _mailHelper = mailHelper;
            _animalRepository = animalRepository;
        }

        // GET: Clients
        public IActionResult Index()
        {
            return View(_clientRepository.GetAll().OrderBy(p => p.Name));
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> DetailsAsync(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            var client = await _clientRepository.GetByIdAsync(id.Value);
            if (client == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Client client)
        {
            if (ModelState.IsValid)
            {
                client.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);

                await _clientRepository.CreateAsync(client);

                //Create User

                var user = await _userHelper.GetUserByEmailAsync(client.Email);

                if (user == null)
                {
                    user = new User
                    {
                        FirstName = client.Name,
                        Email = client.Email,
                        UserName = client.Email
                    };

                    var result = await _userHelper.AddUserAsync(user, "123456789");

                    await _userHelper.AddUserToRoleAsync(user, "Client");

                    var myToken = await _userHelper.GeneratePasswordResetTokenAsync(user);

                    var link = this.Url.Action("ResetPassword", "Account", new { token = myToken }, protocol: HttpContext.Request.Scheme);

                    _mailHelper.SendEmail(user.Email, "Your VetClinic Account",
                    $"Welcome {user.FirstName},<br/> " +
                    $"Your account has been created. Your credentials are:<br/>" +
                    $"Username: {user.Email}<br/>" +
                    $"Password: Change password click in this link:<br/>" +
                    $"<a href = \"{link}\">Reset Password</a><br/><br/>" +
                    $"Thank you for your preference." + "<br/><br/> VetClinic");
                }

                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> EditAsync(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            var client = await _clientRepository.GetByIdAsync(id.Value);
            if (client == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Client client)
        {
            if (id != client.Id)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _clientRepository.UpdateAsync(client);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _clientRepository.ExistsAsync(client.Id))
                    {
                        return new NotFoundViewResult("ClientNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            var client = await _clientRepository.GetByIdAsync(id.Value);
            if (client == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _clientRepository.GetByIdAsync(id);

            var count = _animalRepository.GetAll().Count();

            for (int i = 1; i <= count; i++)
            {
                var animal = await _animalRepository.GetByIdAsync(i);

                if (animal.OwnerId == id)
                {
                    TempData["Message"] = "The client cannot be deleted because it has an animal!";

                    return RedirectToAction(nameof(Index));
                }
            }

            await _clientRepository.DeleteAsync(client);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult ClientNotFound()
        {
            return View();
        }
    }
}

VetClinicFinal/Views/Shared/_Layout.cshtml
@RenderSection("scripts", required: false)

<!DOCTYPE html>
<html>
<head>

    <!-- Basic -->

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- Mobile Metas -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Site Metas -->

    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>VetClinic</title>

    <!-- slider stylesheet -->

    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->

    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!-- fonts style -->

    <link href="https://fonts.googleapis.com/css?family=Dosis:400,500|Poppins:400,700&display=swap" rel="stylesheet">

    <!-- Custom styles for this template -->

    <link href="~/css/style.css" rel="stylesheet" />

    <!-- responsive style -->

    <link href="~/css/responsive.css" rel="stylesheet" />

</head>

<body>
    <div class="hero_area">

        <!-- header section strats -->

        <header class="header_section">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" alt="">
                        <span>
                            VetClinic
                        </span>
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                            <ul class="navbar-nav  ">
                                <li class="nav-item active">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                                </li>
                                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                                    </li>
                                }
                                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Client"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a>
                                    </li>
                                }
                                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Employee"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Communication">Communication</a>
                                    </li>
                                }

                            </ul>
                        </div>
                        <div class="quote_btn-container  d-flex justify-content-center">
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <a asp-area="" asp-controller="" asp-action="">@this.User.Identity.Name &nbsp &nbsp</a>

                                <a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            }
                            else
                            {
                                <a asp-area="" asp-controller="Account" asp-action="Login">Login/Register</a>
                            }

                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <!-- end header section -->

        <div>
            <main role="main">
                @RenderBody()
            </main>
        </div>

        <!-- info section -->

        <section class="info_section layout_padding2">
            <div class="container">
                <div class="info_items">
                    <a href="">
                        <div class="item ">
                            <div class="img-box box-1">
                                <img src="" alt="">
                            </div>
                            <div class="detail-box">
                                <p>
                                    R. Helena Vaz da Silva 4C
                                    1750-429 Lisboa
                                </p>
                            </div>
                        </div>
                    </a>
                    <a href="">
                        <div class="item ">
                            <div class="img-box box-2">
                                <img src="" alt="">
                            </div>
                            <div class="detail-box">
                                <p>
                                    +351911767893
                                </p>
                            </div>
                        </div>
                    </a>
                    <a href="">
                        <div class="item ">
                            <div class="img-box box-3">
                                <img src="" alt="">
                            </div>
                            <div class="detail-box">
                                <p>
                                    vetclinc2021@gmail.com
                                </p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </section>

        <!-- end info_section -->
        <!-- footer section -->

        <section class="container-fluid footer_section">
            <p>
                &copy; 2021 All Rights Reserved By João Pires
            </p>
        </section>

        <!-- footer section -->

        <script type="text/javascript" src="~/js/jquery-3.4.1.min.js"></script>
        <script type="text/javascript" src="~/js/bootstrap.js"></script>

        <!-- script appointments-->

        <script type="text/javascript">
    $(document).ready(function () {
        $("#OwnerId").change(function () {
            $("#AnimalId").empty();
            $.ajax({
                type: 'Post',
                url: '@Url.Action("LoadAnimals")',
                dataType: 'json',
                data: { id: $("#OwnerId").val() },

                success: function (animals) {
                    $.each(animals, function (i, animals) {
                        $("#AnimalId").append('<option value="'
                            + animals.value + '">'
                            + animals.text + '</option>');
                    });
                }
            });
            return false;
        })
    });
        </script>

    </div>
</body>
</html>

VetClinicFinal/Views/Shared/_LayoutViews.cshtml
@RenderSection("scripts", required: false)

<!DOCTYPE html>
<html>
<head>

    <!-- Basic -->

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- Mobile Metas -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Site Metas -->

    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>VetClinic</title>

    <!-- slider stylesheet -->

    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->

    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!-- fonts style -->

    <link href="https://fonts.googleapis.com/css?family=Dosis:400,500|Poppins:400,700&display=swap" rel="stylesheet">

    <!-- Custom styles for this template -->

    <link href="~/css/style.css" rel="stylesheet" />

    <!-- responsive style -->

    <link href="~/css/responsive.css" rel="stylesheet" />

</head>

<body>
    <div class="hero_area">

        <!-- header section strats -->

        <header class="header_section">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" alt="">
                        <span>
                            VetClinic
                        </span>
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                            <ul class="navbar-nav  ">
                                <li class="nav-item active">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                                </li>
                                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                                    </li>
                                }
                                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Client"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a>
                                    </li>
                                }
                                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Employee"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Animals" asp-action="Index">Animals</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Communication">Communication</a>
                                    </li>
                                }

                            </ul>
                        </div>
                        <div class="quote_btn-container  d-flex justify-content-center">
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <a asp-area="" asp-controller="" asp-action="">@this.User.Identity.Name &nbsp &nbsp</a>

                                <a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            }
                            else
                            {
                                <a asp-area="" asp-controller="Account" asp-action="Login">Login/Register</a>
                            }

                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <!-- end header section -->

        <div class="container body-content" style="min-height: 62%; padding-top: 30px">
            @RenderBody()
        </div>

        <!-- info section -->

        <section class="info_section layout_padding2">
            <div class="container">
                <div class="info_items">
                    <a href="">
                        <div class="item ">
                            <div class="img-box box-1">
                                <img src="" alt="">
                            </div>
                            <div class="detail-box">
                                <p>
                                    R. Helena Vaz da Silva 4C
                                    1750-429 Lisboa
                                </p>
                            </div>
                        </div>
                    </a>
                    <a href="">
                        <div class="item ">
                            <div class="img-box box-2">
                                <img src="" alt="">
                            </div>
                            <div class="detail-box">
                                <p>
                                    +351911767893
                                </p>
                            </div>
                        </div>
                    </a>
                    <a href="">
                        <div class="item ">
                            <div class="img-box box-3">
                                <img src="" alt="">
                            </div>
                            <div class="detail-box">
                                <p>
                                    vetclinc2021@gmail.com
                                </p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </section>

        <!-- end info_section -->
        <!-- footer section -->

        <section class="container-fluid footer_section">
            <p>
                &copy; 2021 All Rights Reserved By João Pires
            </p>
        </section>

        <!-- footer section -->

        <script type="text/javascript" src="~/js/jquery-3.4.1.min.js"></script>
        <script type="text/javascript" src="~/js/bootstrap.js"></script>

        <!-- script appointments-->

        <script type="text/javascript">
    $(document).ready(function () {
        $("#OwnerId").change(function () {
            $("#AnimalId").empty();
            $.ajax({
                type: 'Post',
                url: '@Url.Action("LoadAnimals")',
                dataType: 'json',
                data: { id: $("#OwnerId").val() },

                success: function (animals) {
                    $.each(animals, function (i, animals) {
                        $("#AnimalId").append('<option value="'
                            + animals.value + '">'
                            + animals.text + '</option>');
                    });
                }
            });
            return false;
        })
    });
        </script>

    </div>
</body>
</html>